# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Perplex"
license = "Apache 2.0"
licenselink = "https://github.com/bowman2001/perplex/blob/main/LICENSE"
description = "Documentation and multi-purpose theme for technical content"
homepage = "https://perplex.desider.at"
demosite = "https://perplex.desider.at"
tags = ["docs", "blog", "news", "multi-purpose"]
features = ["responsive", "fluid", "dark mode", "accessible", "search", "multi-authors", "taxonomies", "image preprocessing", "typographie" ]
min_version = "0.120.4"
[author]
  name = "Georg Makowski"
  homepage = "https://perplex.desider.at/authors/georg-makowski/"
